name: Build Godot Project

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  export_web:
    name: Export
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true

      - name: Build and export
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./game/
          archive_output: true
          use_preset_export_path: true
          export_debug: false

      # - name: Upload web build to itch
      #   uses: KikimoraGames/itch-publish@v0.0.3
      #   with:
      #     butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
      #     gameData: ./game/bin/web/web.zip
      #     itchUsername: ${{ secrets.ITCH_USER }}
      #     itchGameId: ritual-road
      #     buildChannel: html5

      - name: Upload windows build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ./game/bin/win/RitualRoad_LD55_Windows.zip
          itchUsername: ${{ secrets.ITCH_USER }}
          itchGameId: ritual-road
          buildChannel: windows

      - name: Upload linux build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
            butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
            gameData: ./game/bin/linux/RitualRoad_LD55_Linux.zip
            itchUsername: ${{ secrets.ITCH_USER }}
            itchGameId: ritual-road
            buildChannel: linux
